### ISSUE TITLE
resource is taken

### ISSUE THREAD

**Issue by jiait** [ergo-services/ergo#93]
Call message from remote node, error code is received for the first time: Can't connect to db@172.17.184.57 Resource is taken, continue communication with no problem, not sure whether the initial connection of the node is wrong, or the process connecting to the remote node is wrong? Do you need to ping each other in advance to avoid this problem?

**Comment by halturin** [comment]
If two or more processes are trying to send a message to the peer we haven't connected to yet, it tries to create this connection, so there could be a case of two or more concurrent connection processes. You can workaround this case by just making a connection in advance.

Its already been fixed in the development branch.

**Comment by jiait** [comment]
Thank you. Look forward to updates

**Comment by halturin** [comment]
fixed in 2.1.0
